#!/usr/bin/python3
# -*- coding: UTF-8 -*-

class Solution:
    def subCnt(self, s:str) -> str:
        cnt = 1
        size = len(str)
        pre = s[0]
        ans = ''
        if size == 1:
            ans += '1'
            ans += s[0]

        for i in range(1, size):
            if i == size - 1 or pre != s[i]:
                ans += str(cnt)
                ans += pre
                pre = s[i]
                cnt = 1
            else:
                cnt++
        return ans

    def countAndSay(self, n:int)->str:


def main():
    ss = Solution()
    s = ss.subCnt("12333")
    print(s)
    return

if __name__ == "__main__":
    main()
