#!/bin/bash -e
cd `dirname $0`
if [[ x$1 == x ]]; then
    echo "usage: $0 <file_name>"
    exit -1
fi

file_name=$1
suffix="${file_name##*.}"

if [ ! -f ${file_name} ]; then
    touch $file_name
    if [[ $suffix == cpp ]]; then
        eval cat sample.cpp >> $file_name
    elif [[ $suffix == py ]]; then
        eval cat sample.py >> $file_name
    fi
fi

eval nvim $file_name
