#!/bin/bash -e
#Copyright (c) 2020 Face++, Megvii. All Rights Reserved
#
#@File   : newlt
#@Author : heliwei@megvii.com
#@Date   : 2020-01-02 23:34
#@Brief  : To create a new leetcode solution. 
#
cd `dirname $0`
if [[ x$1 == x ]]; then
    echo "usage: $0 <file_name>"
    exit -1
fi

file_name=$1
suffix="${file_name##*.}"

if [ ! -f ${file_name} ]; then
    #touch $file_name
    if [[ $suffix == cpp ]]; then
		cp ./sample.cpp ../solutions/
		pushd ../solutions/
		eval mv sample.cpp ${file_name}
		popd
    elif [[ $suffix == py ]]; then
		cp ./sample.py ../solutions/
		pushd ../solutions/
		eval mv sample.py ${file_name}
		popd
    fi
fi

pushd ../solutions
eval nvim $file_name +10
popd
